"use client";

import { createContext, useContext, useState, useEffect } from "react";

// ─────────────────────────────────────────────
//  Supported Languages
// ─────────────────────────────────────────────
export const LANGUAGES = [
  { code: "en", label: "English",    flag: "🇬🇧", dir: "ltr" },
  { code: "fr", label: "Français",   flag: "🇫🇷", dir: "ltr" },
  { code: "es", label: "Español",    flag: "🇪🇸", dir: "ltr" },
  { code: "de", label: "Deutsch",    flag: "🇩🇪", dir: "ltr" },
  { code: "ar", label: "العربية",    flag: "🇸🇦", dir: "rtl" },
  { code: "yo", label: "Yorùbá",     flag: "🇳🇬", dir: "ltr" },
  { code: "zh", label: "中文",        flag: "🇨🇳", dir: "ltr" },
];

// ─────────────────────────────────────────────
//  Translations
// ─────────────────────────────────────────────
const translations = {
  en: {
    // Navbar
    signIn: "Sign In",
    dashboard: "Dashboard",
    adminPanel: "Admin Panel",
    logout: "Logout",
    searchPlaceholder: "Search products...",
    settings: "Settings",
    language: "Language",
    // Nav links
    home: "Home",
    shop: "Shop",
    products: "Products",
    categories: "Categories",
    about: "About",
    // Cart
    cart: "Cart",
    emptyCart: "Your cart is empty",
    emptyCartSub: "Looks like you haven't added anything yet.",
    continueShopping: "Continue Shopping",
    removeItem: "Remove",
    orderSummary: "Order Summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    tax: "Tax (15%)",
    total: "Total",
    proceedToCheckout: "Proceed to Checkout",
    freeShipping: "Free",
    // Checkout
    secureCheckout: "Secure Checkout",
    shippingInfo: "Shipping Information",
    paymentMethod: "Payment Method",
    placeOrder: "Place Order",
    address: "Address",
    city: "City",
    country: "Country",
    postalCode: "Postal Code (optional)",
    // Product detail
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    description: "Description",
    reviews: "Reviews",
    specifications: "Specifications",
    writeReview: "Write a Review",
    submitReview: "Submit Review",
    yourRating: "Your Rating",
    yourComment: "Your Comment",
    commentPlaceholder: "Share your experience with this product...",
    alreadyReviewed: "You have already reviewed this product. Thank you!",
    loginToReview: "You must be logged in to leave a review.",
    noReviews: "No reviews yet. Be the first!",
    reviewSuccess: "Your review has been submitted! Thank you.",
    selectRating: "Please select a star rating.",
    writeComment: "Please write a comment.",
    // Labels
    poor: "Poor",
    fair: "Fair",
    good: "Good",
    veryGood: "Very Good",
    excellent: "Excellent",
    // Misc
    loading: "Loading...",
    submitting: "Submitting...",
    viewAll: "View All",
    shopNow: "Shop Now",
    newArrivals: "New Arrivals",
    featuredProducts: "Featured Products",
    noProductsFound: "No products found.",
    price: "Price",
    quantity: "Quantity",

    // Footer
    freeDelivery: "Free Delivery",
    freeDeliverySub: "On orders over $500",
    securePayments: "Secure Payments",
    securePaymentsSub: "100% protected transfers",
    optimusTransfer: "Optimus Bank Transfer",
    optimusTransferSub: "Acc: 2002245072 · Donald Ekemini David",
    brandDescription: "Premium home appliances and furniture. Crafting beautiful, modern living spaces tailored just for you.",
    quickLinks: "Shop",
    allProducts: "All Products",
    livingRoom: "Living Room",
    kitchen: "Kitchen Appliances",
    bedroom: "Bedroom",
    office: "Office",
    support: "Support",
    myAccount: "My Account",
    trackOrder: "Track Order",
    returnsExchanges: "Returns & Exchanges",
    contactUs: "Contact Us",
    stayConnected: "Stay Connected",
    subscribeDeals: "Subscribe for deals & updates",
    go: "Go",
    copyright: "All rights reserved.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    cookiePolicy: "Cookie Policy",

    // AuthModal
    welcomeBack: "Welcome Back",
    joinBIGDON: "Join BIGDON",
    welcomeBackSub: "Sign in to access your premium account",
    joinBIGDONSub: "Create an account to track orders and save wishlists",
    fullName: "Full Name",
    emailAddress: "Email Address",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    logIn: "Log In",
    passwordsDoNotMatch: "Passwords do not match",

    // Shop Page
    filters: "Filters",
    sortBy: "Sort By",
    clearAllFilters: "Clear all filters",
    searchResultsFor: "Search Results for",
    shopCollection: "Shop Collection",
    shopSub: "Discover our premium range of products to elevate your space.",
    sortNewest: "New Arrivals",
    sortLowest: "Price: Low to High",
    sortHighest: "Price: High to Low",
    sortPopular: "Most Popular",
    noProductsFoundSub: "We couldn't find any products matching your criteria.",

    // Home Page
    shopCollectionBtn: "Shop Collection",
    shopByCategory: "Shop By Category",
    categorySub: "Curated essentials for every space.",
    slideTitle1: "Elevate Your\nLiving Space.",
    slideDesc1: "Discover premium furniture and appliances designed for the modern home.",
    slideTitle2: "Culinary\nExcellence.",
    slideDesc2: "State-of-the-art kitchen appliances for the passionate home chef.",
    slideTitle3: "Restful\nSanctuary.",
    slideDesc3: "Create your perfect bedroom retreat with our luxury collections.",
    yearWarranty: "1 Year Warranty",
    warrantySub: "Guaranteed product quality",
    securePaymentsBadge: "Secure Payments",
    securePaymentsBadgeSub: "100% secure checkout",
    supportBadge: "24/7 Support",
    supportBadgeSub: "Live chat with our team",
      myWishlist: "My Wishlist",
    emptyWishlist: "Your wishlist is empty",
    discoverProducts: "Discover products",
    moveToCart: "Move to Cart",
},

  fr: {
    signIn: "Se Connecter",
    dashboard: "Tableau de Bord",
    adminPanel: "Panneau Admin",
    logout: "Déconnexion",
    searchPlaceholder: "Rechercher des produits...",
    settings: "Paramètres",
    language: "Langue",
    home: "Accueil",
    shop: "Boutique",
    products: "Produits",
    categories: "Catégories",
    about: "À Propos",
    cart: "Panier",
    emptyCart: "Votre panier est vide",
    emptyCartSub: "Vous n'avez encore rien ajouté.",
    continueShopping: "Continuer les Achats",
    removeItem: "Supprimer",
    orderSummary: "Récapitulatif",
    subtotal: "Sous-total",
    shipping: "Livraison",
    tax: "Taxe (15%)",
    total: "Total",
    proceedToCheckout: "Passer à la Caisse",
    freeShipping: "Gratuit",
    secureCheckout: "Paiement Sécurisé",
    shippingInfo: "Informations de Livraison",
    paymentMethod: "Méthode de Paiement",
    placeOrder: "Passer la Commande",
    address: "Adresse",
    city: "Ville",
    country: "Pays",
    postalCode: "Code Postal (optionnel)",
    addToCart: "Ajouter au Panier",
    buyNow: "Acheter Maintenant",
    inStock: "En Stock",
    outOfStock: "Rupture de Stock",
    description: "Description",
    reviews: "Avis",
    specifications: "Spécifications",
    writeReview: "Écrire un Avis",
    submitReview: "Soumettre l'Avis",
    yourRating: "Votre Note",
    yourComment: "Votre Commentaire",
    commentPlaceholder: "Partagez votre expérience avec ce produit...",
    alreadyReviewed: "Vous avez déjà évalué ce produit. Merci!",
    loginToReview: "Vous devez être connecté pour laisser un avis.",
    noReviews: "Aucun avis pour l'instant. Soyez le premier!",
    reviewSuccess: "Votre avis a été soumis! Merci.",
    selectRating: "Veuillez sélectionner une note en étoiles.",
    writeComment: "Veuillez écrire un commentaire.",
    poor: "Médiocre",
    fair: "Passable",
    good: "Bien",
    veryGood: "Très Bien",
    excellent: "Excellent",
    loading: "Chargement...",
    submitting: "Envoi en cours...",
    viewAll: "Voir Tout",
    shopNow: "Acheter Maintenant",
    newArrivals: "Nouveautés",
    featuredProducts: "Produits Vedettes",
    noProductsFound: "Aucun produit trouvé.",
    price: "Prix",
    quantity: "Quantité",

    // Added
    freeDelivery: "Livraison Gratuite",
    freeDeliverySub: "Pour les commandes de plus de 500 $",
    securePayments: "Paiements Sécurisés",
    securePaymentsSub: "Transferts 100% sécurisés",
    optimusTransfer: "Transfert Optimus Bank",
    optimusTransferSub: "Compte: 2002245072 · Donald Ekemini David",
    brandDescription: "Appareils électroménagers et meubles de qualité supérieure. Créez des espaces de vie modernes et magnifiques sur mesure.",
    quickLinks: "Boutique",
    allProducts: "Tous les produits",
    livingRoom: "Salon",
    kitchen: "Cuisine",
    bedroom: "Chambre à coucher",
    office: "Bureau",
    support: "Assistance",
    myAccount: "Mon Compte",
    trackOrder: "Suivre la Commande",
    returnsExchanges: "Retours & Échanges",
    contactUs: "Contactez-nous",
    stayConnected: "Restez Connecté",
    subscribeDeals: "Abonnez-vous aux offres & mises à jour",
    go: "Aller",
    copyright: "Tous droits réservés.",
    privacyPolicy: "Politique de Confidentialité",
    termsOfService: "Conditions d'utilisation",
    cookiePolicy: "Politique relative aux cookies",
    welcomeBack: "Bon retour",
    joinBIGDON: "Rejoindre BIGDON",
    welcomeBackSub: "Connectez-vous pour accéder à votre compte premium",
    joinBIGDONSub: "Créez un compte pour suivre vos commandes et sauvegarder vos favoris",
    fullName: "Nom Complet",
    emailAddress: "Adresse E-mail",
    passwordLabel: "Mot de passe",
    confirmPasswordLabel: "Confirmer le mot de passe",
    createAccount: "Créer un Compte",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
    logIn: "Se Connecter",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas",
    filters: "Filtres",
    sortBy: "Trier Par",
    clearAllFilters: "Effacer tous les filtres",
    searchResultsFor: "Résultats de recherche pour",
    shopCollection: "Boutique de Collection",
    shopSub: "Découvrez notre gamme premium de produits pour embellir votre espace.",
    sortNewest: "Nouveautés",
    sortLowest: "Prix : Du - au + cher",
    sortHighest: "Prix : Du + au - cher",
    sortPopular: "Plus Populaire",
    noProductsFoundSub: "Nous n'avons trouvé aucun produit correspondant à vos critères.",
    shopCollectionBtn: "Acheter la collection",
    shopByCategory: "Acheter par catégorie",
    categorySub: "Sélection d'essentiels pour chaque espace.",
    slideTitle1: "Sublimez Votre\nEspace de Vie.",
    slideDesc1: "Découvrez des meubles et appareils de qualité supérieure pour la maison moderne.",
    slideTitle2: "Excellence\nCulinaire.",
    slideDesc2: "Appareils de cuisine de pointe pour le chef amateur passionné.",
    slideTitle3: "Sanctuaire de\nTranquillité.",
    slideDesc3: "Créez votre refuge idéal de chambre avec nos collections de luxe.",
    yearWarranty: "Garantie 1 An",
    warrantySub: "Qualité de produit garantie",
    securePaymentsBadge: "Paiements Sécurisés",
    securePaymentsBadgeSub: "Paiement 100% sécurisé",
    supportBadge: "Support 24h/24 7j/7",
    supportBadgeSub: "Discutez en direct avec notre équipe",
      myWishlist: "Ma Liste d'Envies",
    emptyWishlist: "Votre liste d'envies est vide",
    discoverProducts: "Découvrir des produits",
    moveToCart: "Déplacer vers le Panier",
},

  es: {
    signIn: "Iniciar Sesión",
    dashboard: "Panel de Control",
    adminPanel: "Panel de Admin",
    logout: "Cerrar Sesión",
    searchPlaceholder: "Buscar productos...",
    settings: "Configuración",
    language: "Idioma",
    home: "Inicio",
    shop: "Tienda",
    products: "Productos",
    categories: "Categorías",
    about: "Acerca de",
    cart: "Carrito",
    emptyCart: "Tu carrito está vacío",
    emptyCartSub: "Parece que no has añadido nada todavía.",
    continueShopping: "Continuar Comprando",
    removeItem: "Eliminar",
    orderSummary: "Resumen del Pedido",
    subtotal: "Subtotal",
    shipping: "Envío",
    tax: "Impuesto (15%)",
    total: "Total",
    proceedToCheckout: "Proceder al Pago",
    freeShipping: "Gratis",
    secureCheckout: "Pago Seguro",
    shippingInfo: "Información de Envío",
    paymentMethod: "Método de Pago",
    placeOrder: "Realizar Pedido",
    address: "Dirección",
    city: "Ciudad",
    country: "País",
    postalCode: "Código Postal (opcional)",
    addToCart: "Añadir al Carrito",
    buyNow: "Comprar Ahora",
    inStock: "En Stock",
    outOfStock: "Sin Stock",
    description: "Descripción",
    reviews: "Reseñas",
    specifications: "Especificaciones",
    writeReview: "Escribir Reseña",
    submitReview: "Enviar Reseña",
    yourRating: "Tu Valoración",
    yourComment: "Tu Comentario",
    commentPlaceholder: "Comparte tu experiencia con este producto...",
    alreadyReviewed: "Ya has reseñado este producto. ¡Gracias!",
    loginToReview: "Debes iniciar sesión para dejar una reseña.",
    noReviews: "Aún no hay reseñas. ¡Sé el primero!",
    reviewSuccess: "¡Tu reseña ha sido enviada! Gracias.",
    selectRating: "Por favor selecciona una valoración.",
    writeComment: "Por favor escribe un comentario.",
    poor: "Malo",
    fair: "Regular",
    good: "Bueno",
    veryGood: "Muy Bueno",
    excellent: "Excelente",
    loading: "Cargando...",
    submitting: "Enviando...",
    viewAll: "Ver Todo",
    shopNow: "Comprar Ahora",
    newArrivals: "Novedades",
    featuredProducts: "Productos Destacados",
    noProductsFound: "No se encontraron productos.",
    price: "Precio",
    quantity: "Cantidad",

    // Added
    freeDelivery: "Envío Gratis",
    freeDeliverySub: "En pedidos superiores a $500",
    securePayments: "Pagos Seguros",
    securePaymentsSub: "Transferencias 100% protegidas",
    optimusTransfer: "Transferencia Optimus Bank",
    optimusTransferSub: "Cuenta: 2002245072 · Donald Ekemini David",
    brandDescription: "Electrodomésticos y muebles de primera calidad. Creando espacios de vida hermosos y modernos diseñados para usted.",
    quickLinks: "Tienda",
    allProducts: "Todos los Productos",
    livingRoom: "Sala de Estar",
    kitchen: "Cocina",
    bedroom: "Dormitorio",
    office: "Oficina",
    support: "Soporte",
    myAccount: "Mi Cuenta",
    trackOrder: "Seguimiento de Pedido",
    returnsExchanges: "Devoluciones & Cambios",
    contactUs: "Contáctenos",
    stayConnected: "Mantente Conectado",
    subscribeDeals: "Suscríbete para ofertas y actualizaciones",
    go: "Ir",
    copyright: "Todos los derechos reservados.",
    privacyPolicy: "Política de Privacidad",
    termsOfService: "Términos de Servicio",
    cookiePolicy: "Política de Cookies",
    welcomeBack: "Bienvenido de Nuevo",
    joinBIGDON: "Únete a BIGDON",
    welcomeBackSub: "Inicia sesión para acceder a tu cuenta premium",
    joinBIGDONSub: "Crea una cuenta para rastrear pedidos y guardar favoritos",
    fullName: "Nombre Completo",
    emailAddress: "Dirección de E-mail",
    passwordLabel: "Contraseña",
    confirmPasswordLabel: "Confirmar Contraseña",
    createAccount: "Crear Cuenta",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    dontHaveAccount: "¿No tienes una cuenta?",
    signUp: "Registrarse",
    logIn: "Iniciar Sesión",
    passwordsDoNotMatch: "Las contraseñas no coinciden",
    filters: "Filtros",
    sortBy: "Ordenar Por",
    clearAllFilters: "Borrar todos los filtros",
    searchResultsFor: "Resultados de búsqueda para",
    shopCollection: "Comprar Colección",
    shopSub: "Descubra nuestra gama premium de productos para mejorar su espacio.",
    sortNewest: "Novedades",
    sortLowest: "Precio: Menor a Mayor",
    sortHighest: "Precio: Mayor a Menor",
    sortPopular: "Más Popular",
    noProductsFoundSub: "No pudimos encontrar ningún producto que coincida con sus criterios.",
    shopCollectionBtn: "Comprar Colección",
    shopByCategory: "Comprar Por Categoría",
    categorySub: "Esenciales curados para cada espacio.",
    slideTitle1: "Eleva Tu\nEspacio Vital.",
    slideDesc1: "Descubre muebles y electrodomésticos premium diseñados para el hogar moderno.",
    slideTitle2: "Excelencia\nCulinaria.",
    slideDesc2: "Electrodomésticos de cocina de última generación para el chef apasionado.",
    slideTitle3: "Santuario de\nDescanso.",
    slideDesc3: "Crea tu retiro de dormitorio perfecto con nuestras colecciones de lujo.",
    yearWarranty: "Garantía de 1 Año",
    warrantySub: "Calidad de producto garantizada",
    securePaymentsBadge: "Pagos Seguros",
    securePaymentsBadgeSub: "Pago 100% seguro",
    supportBadge: "Soporte 24/7",
    supportBadgeSub: "Chat en vivo con nuestro equipo",
      myWishlist: "Mi Lista de Deseos",
    emptyWishlist: "Tu lista de deseos está vacía",
    discoverProducts: "Descubrir productos",
    moveToCart: "Mover al Carrito",
},

  de: {
    signIn: "Anmelden",
    dashboard: "Dashboard",
    adminPanel: "Admin-Panel",
    logout: "Abmelden",
    searchPlaceholder: "Produkte suchen...",
    settings: "Einstellungen",
    language: "Sprache",
    home: "Startseite",
    shop: "Shop",
    products: "Produkte",
    categories: "Kategorien",
    about: "Über uns",
    cart: "Warenkorb",
    emptyCart: "Ihr Warenkorb ist leer",
    emptyCartSub: "Sie haben noch nichts hinzugefügt.",
    continueShopping: "Weiter Einkaufen",
    removeItem: "Entfernen",
    orderSummary: "Bestellübersicht",
    subtotal: "Zwischensumme",
    shipping: "Versand",
    tax: "Steuer (15%)",
    total: "Gesamt",
    proceedToCheckout: "Zur Kasse",
    freeShipping: "Kostenlos",
    secureCheckout: "Sicher Bezahlen",
    shippingInfo: "Versandinformationen",
    paymentMethod: "Zahlungsmethode",
    placeOrder: "Bestellung Aufgeben",
    address: "Adresse",
    city: "Stadt",
    country: "Land",
    postalCode: "Postleitzahl (optional)",
    addToCart: "In den Warenkorb",
    buyNow: "Jetzt Kaufen",
    inStock: "Auf Lager",
    outOfStock: "Nicht Vorrätig",
    description: "Beschreibung",
    reviews: "Bewertungen",
    specifications: "Spezifikationen",
    writeReview: "Bewertung Schreiben",
    submitReview: "Bewertung Absenden",
    yourRating: "Ihre Bewertung",
    yourComment: "Ihr Kommentar",
    commentPlaceholder: "Teilen Sie Ihre Erfahrung mit diesem Produkt...",
    alreadyReviewed: "Sie haben dieses Produkt bereits bewertet. Danke!",
    loginToReview: "Sie müssen angemeldet sein, um eine Bewertung abzugeben.",
    noReviews: "Noch keine Bewertungen. Seien Sie der Erste!",
    reviewSuccess: "Ihre Bewertung wurde eingereicht! Danke.",
    selectRating: "Bitte wählen Sie eine Sternbewertung.",
    writeComment: "Bitte schreiben Sie einen Kommentar.",
    poor: "Schlecht",
    fair: "Befriedigend",
    good: "Gut",
    veryGood: "Sehr Gut",
    excellent: "Ausgezeichnet",
    loading: "Wird geladen...",
    submitting: "Wird gesendet...",
    viewAll: "Alle Anzeigen",
    shopNow: "Jetzt Kaufen",
    newArrivals: "Neuankömmlinge",
    featuredProducts: "Empfohlene Produkte",
    noProductsFound: "Keine Produkte gefunden.",
    price: "Preis",
    quantity: "Menge",

    // Added
    freeDelivery: "Kostenlose Lieferung",
    freeDeliverySub: "Bei Bestellungen über 500 $",
    securePayments: "Sichere Zahlungen",
    securePaymentsSub: "100% geschützte Überweisungen",
    optimusTransfer: "Optimus Banküberweisung",
    optimusTransferSub: "Kto: 2002245072 · Donald Ekemini David",
    brandDescription: "Premium-Haushaltsgeräte und -Möbel. Wir schaffen schöne, moderne Wohnräume, die auf Sie zugeschnitten sind.",
    quickLinks: "Shop",
    allProducts: "Alle Produkte",
    livingRoom: "Wohnzimmer",
    kitchen: "Küche",
    bedroom: "Schlafzimmer",
    office: "Büro",
    support: "Kundendienst",
    myAccount: "Mein Konto",
    trackOrder: "Bestellung Verfolgen",
    returnsExchanges: "Rückgabe & Umtausch",
    contactUs: "Kontaktieren Sie uns",
    stayConnected: "Bleib in Verbindung",
    subscribeDeals: "Abonnieren Sie Angebote & Updates",
    go: "Los",
    copyright: "Alle Rechte vorbehalten.",
    privacyPolicy: "Datenschutzerklärung",
    termsOfService: "Nutzungsbedingungen",
    cookiePolicy: "Cookie-Richtlinie",
    welcomeBack: "Willkommen zurück",
    joinBIGDON: "Mitglied werden",
    welcomeBackSub: "Melden Sie sich an, um auf Ihr Premium-Konto zuzugreifen",
    joinBIGDONSub: "Erstellen Sie ein Konto, um Bestellungen zu verfolgen und Merklisten zu speichern",
    fullName: "Vollständiger Name",
    emailAddress: "E-Mail-Adresse",
    passwordLabel: "Passwort",
    confirmPasswordLabel: "Passwort bestätigen",
    createAccount: "Konto erstellen",
    alreadyHaveAccount: "Haben Sie bereits ein Konto?",
    dontHaveAccount: "Haben Sie noch kein Konto?",
    signUp: "Registrieren",
    logIn: "Anmelden",
    passwordsDoNotMatch: "Passwörter stimmen nicht überein",
    filters: "Filter",
    sortBy: "Sortieren nach",
    clearAllFilters: "Alle Filter löschen",
    searchResultsFor: "Suchergebnisse für",
    shopCollection: "Kollektion shoppen",
    shopSub: "Entdecken Sie unser Premium-Sortiment, um Ihr Zuhause zu verschönern.",
    sortNewest: "Neuankömmlinge",
    sortLowest: "Preis: Aufsteigend",
    sortHighest: "Price: Absteigend",
    sortPopular: "Beliebteste",
    noProductsFoundSub: "Wir konnten keine Produkte finden, die Ihren Kriterien entsprechen.",
    shopCollectionBtn: "Kollektion shoppen",
    shopByCategory: "Nach Kategorie shoppen",
    categorySub: "Ausgesuchte Essentials für jeden Raum.",
    slideTitle1: "Werten Sie Ihr\nWohnzimmer auf.",
    slideDesc1: "Entdecken Sie Premium-Möbel und -Geräte für das moderne Zuhause.",
    slideTitle2: "Kulinarische\nExzellenz.",
    slideDesc2: "Modernste Küchengeräte für den leidenschaftlichen Hobbykoch.",
    slideTitle3: "Erholsame\nOase.",
    slideDesc3: "Schaffen Sie mit unseren Luxuskollektionen den perfekten Rückzugsort im Schlafzimmer.",
    yearWarranty: "1 Jahr Garantie",
    warrantySub: "Garantierte Produktqualität",
    securePaymentsBadge: "Sichere Zahlungen",
    securePaymentsBadgeSub: "100% sicherer Checkout",
    supportBadge: "24/7 Support",
    supportBadgeSub: "Live-Chat mit unserem Team",
      myWishlist: "Meine Wunschliste",
    emptyWishlist: "Ihre Wunschliste ist leer",
    discoverProducts: "Produkte entdecken",
    moveToCart: "In den Warenkorb",
},

  ar: {
    signIn: "تسجيل الدخول",
    dashboard: "لوحة التحكم",
    adminPanel: "لوحة الإدارة",
    logout: "تسجيل الخروج",
    searchPlaceholder: "البحث عن المنتجات...",
    settings: "الإعدادات",
    language: "اللغة",
    home: "الرئيسية",
    shop: "المتجر",
    products: "المنتجات",
    categories: "الفئات",
    about: "من نحن",
    cart: "عربة التسوق",
    emptyCart: "سلة التسوق فارغة",
    emptyCartSub: "لم تضف أي منتجات بعد.",
    continueShopping: "مواصلة التسوق",
    removeItem: "إزالة",
    orderSummary: "ملخص الطلب",
    subtotal: "المجموع الجزئي",
    shipping: "الشحن",
    tax: "الضريبة (15%)",
    total: "الإجمالي",
    proceedToCheckout: "إتمام الشراء",
    freeShipping: "مجاني",
    secureCheckout: "دفع آمن",
    shippingInfo: "معلومات الشحن",
    paymentMethod: "طريقة الدفع",
    placeOrder: "تأكيد الطلب",
    address: "العنوان",
    city: "المدينة",
    country: "البلد",
    postalCode: "الرمز البريدي (اختياري)",
    addToCart: "أضف إلى العربة",
    buyNow: "اشتر الآن",
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    description: "الوصف",
    reviews: "التقييمات",
    specifications: "المواصفات",
    writeReview: "كتابة تقييم",
    submitReview: "إرسال التقييم",
    yourRating: "تقييمك",
    yourComment: "تعليقك",
    commentPlaceholder: "شارك تجربتك مع هذا المنتج...",
    alreadyReviewed: "لقد قمت بالفعل بتقييم هذا المنتج. شكراً!",
    loginToReview: "يجب تسجيل الدخول لترك تقييم.",
    noReviews: "لا توجد تقييمات بعد. كن الأول!",
    reviewSuccess: "تم إرسال تقييمك! شكراً.",
    selectRating: "الرجاء تحديد تقييم بالنجوم.",
    writeComment: "الرجاء كتابة تعليق.",
    poor: "ضعيف",
    fair: "مقبول",
    good: "جيد",
    veryGood: "جيد جداً",
    excellent: "ممتاز",
    loading: "جارٍ التحميل...",
    submitting: "جارٍ الإرسال...",
    viewAll: "عرض الكل",
    shopNow: "تسوق الآن",
    newArrivals: "الوافدون الجدد",
    featuredProducts: "منتجات مميزة",
    noProductsFound: "لم يتم العثور على منتجات.",
    price: "السعر",
    quantity: "الكمية",

    // Added
    freeDelivery: "شحن مجاني",
    freeDeliverySub: "على الطلبات الأكثر من $500",
    securePayments: "دفع آمن",
    securePaymentsSub: "تحويلات محمية 100%",
    optimusTransfer: "تحويل بنك أوبتيموس",
    optimusTransferSub: "حساب: 2002245072 · دونالد إيكيميني ديفيد",
    brandDescription: "أجهزة منزلية وأثاث فاخر. نقوم بتصميم مساحات معيشة جميلة وعصرية مصممة خصيصاً لك.",
    quickLinks: "المتجر",
    allProducts: "جميع المنتجات",
    livingRoom: "غرفة المعيشة",
    kitchen: "المطبخ",
    bedroom: "غرفة النوم",
    office: "المكتب",
    support: "الدعم الفني",
    myAccount: "حسابي",
    trackOrder: "تتبع الطلب",
    returnsExchanges: "المرتجعات والمستبدلات",
    contactUs: "اتصل بنا",
    stayConnected: "كن على اتصال",
    subscribeDeals: "اشترك للحصول على العروض والتحديثات",
    go: "ذهاب",
    copyright: "جميع الحقوق محفوظة.",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    cookiePolicy: "سياسة ملفات الارتباط",
    welcomeBack: "مرحباً بعودتك",
    joinBIGDON: "انضم إلى BIGDON",
    welcomeBackSub: "سجل الدخول للوصول إلى حسابك المميز",
    joinBIGDONSub: "أنشئ حساباً لتتبع طلباتك وحفظ قائمة رغباتك",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    passwordLabel: "كلمة المرور",
    confirmPasswordLabel: "تأكيد كلمة المرور",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    signUp: "تسجيل",
    logIn: "تسجيل الدخول",
    passwordsDoNotMatch: "كلمات المرور غير متطابقة",
    filters: "تصفية",
    sortBy: "ترتيب حسب",
    clearAllFilters: "مسح جميع الفلاتر",
    searchResultsFor: "نتائج البحث عن",
    shopCollection: "تسوق المجموعة",
    shopSub: "اكتشف مجموعتنا المتميزة من المنتجات للارتقاء بمساحتك الخاصة.",
    sortNewest: "الوافدون الجدد",
    sortLowest: "السعر: من الأقل إلى الأعلى",
    sortHighest: "السعر: من الأعلى إلى الأقل",
    sortPopular: "الأكثر شعبية",
    noProductsFoundSub: "لم نتمكن من العثور على أي منتجات تطابق معاييرك.",
    shopCollectionBtn: "تسوق المجموعة",
    shopByCategory: "تسوق حسب الفئة",
    categorySub: "أساسيات منسقة لكل مساحة.",
    slideTitle1: "ارتقِ بمساحة\nمعيشتك.",
    slideDesc1: "اكتشف الأثاث والأجهزة المنزلية المتميزة المصممة للمنزل الحديث.",
    slideTitle2: "التميز في\nالطهي.",
    slideDesc2: "أحدث أجهزة المطبخ للطاهي المنزلي الشغوف.",
    slideTitle3: "ملاذ\nمريح.",
    slideDesc3: "أنشئ غرفة النوم المثالية للاسترخاء مع مجموعتنا الفاخرة.",
    yearWarranty: "ضمان لمدة سنة",
    warrantySub: "جودة المنتج مضمونة",
    securePaymentsBadge: "دفع آمن",
    securePaymentsBadgeSub: "إتمام الشراء آمن 100%",
    supportBadge: "دعم على مدار الساعة",
    supportBadgeSub: "محادثة مباشرة مع فريقنا",
      myWishlist: "قائمة رغباتي",
    emptyWishlist: "قائمة رغباتك فارغة",
    discoverProducts: "اكتشف المنتجات",
    moveToCart: "نقل إلى العربة",
},

  yo: {
    signIn: "Wọlé",
    dashboard: "Pánẹ́ẹ̀lì",
    adminPanel: "Pánẹ́ẹ̀lì Alámòjútó",
    logout: "Jáde",
    searchPlaceholder: "Wá àwọn ẹrù...",
    settings: "Ìtò",
    language: "Èdè",
    home: "Ilé",
    shop: "Ọjà",
    products: "Àwọn Ẹrù",
    categories: "Àwọn Ẹ̀ka",
    about: "Nípa Wa",
    cart: "Agbọ̀n Rírà",
    emptyCart: "Agbọ̀n rẹ ò ní ohunkóhun",
    emptyCartSub: "O ò tí ì fi ohunkóhun sí.",
    continueShopping: "Tẹ̀síwájú Rírà",
    removeItem: "Yọ Kúrò",
    orderSummary: "Àkópọ̀ Àṣẹ",
    subtotal: "Àpapọ̀ Kékeré",
    shipping: "Gbígba Ẹrù",
    tax: "Owó-Orí (15%)",
    total: "Àpapọ̀",
    proceedToCheckout: "Lọ Sí Ìsanwó",
    freeShipping: "Ọfẹ",
    secureCheckout: "Ìsanwó Aabo",
    shippingInfo: "Àlàyé Ìfiránṣẹ̀",
    paymentMethod: "Ọ̀nà Ìsanwó",
    placeOrder: "Ṣe Àṣẹ",
    address: "Àdírẹ́ẹ̀sì",
    city: "Ìlú",
    country: "Orílẹ̀-èdè",
    postalCode: "Kóòdù Àpò Lẹ́tà (aṣayan)",
    addToCart: "Fi Sí Agbọ̀n",
    buyNow: "Rà Báyìí",
    inStock: "Wà Ní Àkójọpọ̀",
    outOfStock: "Kò Sí Mọ́",
    description: "Àpèjúwe",
    reviews: "Àwọn Ìdánilẹ́kọ̀ọ́",
    specifications: "Àwọn Ìpínrọ̀",
    writeReview: "Kọ Ìdánilẹ́kọ̀ọ́",
    submitReview: "Firanṣẹ Ìdánilẹ́kọ̀ọ́",
    yourRating: "Ìdíyelé Rẹ",
    yourComment: "Ìhun Rẹ",
    commentPlaceholder: "Pin ìrírí rẹ nípa ẹrù yìí...",
    alreadyReviewed: "O ti ṣe àgbéyẹ̀wò tẹ́lẹ̀. E ṣeun!",
    loginToReview: "O gbọdọ̀ wọlé láti fi ìdánilẹ́kọ̀ọ́ sílẹ̀.",
    noReviews: "Kò sí àgbéyẹ̀wò. Jẹ́ ẹni àkọ́kọ́!",
    reviewSuccess: "Àgbéyẹ̀wò rẹ ti fi ranṣẹ! E ṣeun.",
    selectRating: "Jọwọ yan ìdíyelé ìràwọ̀.",
    writeComment: "Jọwọ kọ ìhun kan.",
    poor: "Burú",
    fair: "Dára Die",
    good: "Dára",
    veryGood: "Dára Púpọ̀",
    excellent: "Ìyanu",
    loading: "Ń gbéru...",
    submitting: "Ń firanṣẹ...",
    viewAll: "Wo Gbogbo",
    shopNow: "Rà Báyìí",
    newArrivals: "Àwọn Tuntun",
    featuredProducts: "Àwọn Ẹrù Àkànjọ",
    noProductsFound: "Kò sí ẹrù tí a rí.",
    price: "Iye Owó",
    quantity: "Iye",

    // Added
    freeDelivery: "Fún Ọfẹ",
    freeDeliverySub: "Fun awọn aṣẹ to ju $500",
    securePayments: "Sanwo Aabo",
    securePaymentsSub: "100% awọn gbigbe to ni aabo",
    optimusTransfer: "Gbigbe Optimus Bank",
    optimusTransferSub: "Acc: 2002245072 · Donald Ekemini David",
    brandDescription: "Awọn ohun elo ile ti o ni agbara giga ati aga. Ṣiṣe awọn aaye gbigbe ti o lẹwa ati ti ode oni fun ọ.",
    quickLinks: "Rà",
    allProducts: "Gbogbo Ẹrù",
    livingRoom: "Iyàrá Gbọ̀ngàn",
    kitchen: "Iyàrá Ìdáná",
    bedroom: "Iyàrá Sùn",
    office: "Ọ́fíìsì",
    support: "Ìrànwọ́",
    myAccount: "Àkáǹtì Mi",
    trackOrder: "Tọpinpin Àṣẹ",
    returnsExchanges: "Yíyípo & Pàṣípàrọ̀",
    contactUs: "Kàn Sí Wa",
    stayConnected: "Duro ni Isopọ",
    subscribeDeals: "Alabapin fun awọn ipese & awọn imudojuiwọn",
    go: "Lọ",
    copyright: "Gbogbo ẹtọ wa ni ipamọ.",
    privacyPolicy: "Ìlànà Àṣírí",
    termsOfService: "Awọn Tíì̀mù Iṣẹ́",
    cookiePolicy: "Ìlànà Kúkì",
    welcomeBack: "Kaabọ Pada",
    joinBIGDON: "Darapọ mọ BIGDON",
    welcomeBackSub: "Wọle lati wọle si akọọlẹ Ere rẹ",
    joinBIGDONSub: "Ṣẹda akọọlẹ kan lati tọpinpin awọn aṣẹ ati fipamọ awọn ayanfẹ",
    fullName: "Orukọ Kikun",
    emailAddress: "Àdírẹ́sì Imeeli",
    passwordLabel: "Kọkọrọ Aṣiri",
    confirmPasswordLabel: "Fidi Kọkọrọ Aṣiri Mulẹ",
    createAccount: "Ṣẹda Akọọlẹ",
    alreadyHaveAccount: "Ṣe o ti ni akọọlẹ tẹlẹ̀?",
    dontHaveAccount: "Ṣe o ko ni akọọlẹ kan?",
    signUp: "Forukọsilẹ",
    logIn: "Wọlé",
    passwordsDoNotMatch: "Awọn kọkọrọ aṣiri ko baramu",
    filters: "Awọn Ajọ",
    sortBy: "Too Nipa",
    clearAllFilters: "Pa gbogbo awọn ajọ rẹ kuro",
    searchResultsFor: "Awọn abajade wiwa fun",
    shopCollection: "Kojọpọ Ọjà",
    shopSub: "Ṣawari ibiti o dara julọ of awọn ẹrù lati gbe aaye rẹ ga.",
    sortNewest: "Awọn Tuntun",
    sortLowest: "Iye: Kekere si Giga",
    sortHighest: "Iye: Giga si Kekere",
    sortPopular: "Gbajúmọ̀ Jùlọ",
    noProductsFoundSub: "A ko le wa eyikeyi awọn ẹrù ti o baamu awọn ibeere rẹ.",
    shopCollectionBtn: "Ra Gbogbo Rẹ",
    shopByCategory: "Ra Nipa Ẹ̀ka",
    categorySub: "Awọn ohun pataki fun gbogbo aaye.",
    slideTitle1: "Gbé Aaye Rẹ\nGa Pẹlu Aṣa.",
    slideDesc1: "Ṣawari ohun ọṣọ Ere ati awọn ohun elo ti a ṣe fun ile ode oni.",
    slideTitle2: "Ìdáná\nTí Ó Kẹ́kọ̀ọ́.",
    slideDesc2: "Awọn ohun elo ibi idana ounjẹ ti ode oni fun olounjẹ ile ti o nifẹ si.",
    slideTitle3: "Ibi Ìsinmi\nTí Ó Dákẹ́ jẹ́ẹ́.",
    slideDesc3: "Ṣẹda ibi isinmi yara yara pipe rẹ pẹlu awọn ikojọpọ igbadun wa.",
    yearWarranty: "Atilẹyin Ọdun Kan",
    warrantySub: "Didara ọja ti o ni idaniloju",
    securePaymentsBadge: "Ìsanwó Aabo",
    securePaymentsBadgeSub: "100% isanwo aabo",
    supportBadge: "Atilẹyin 24/7",
    supportBadgeSub: "Sọrọ laaye pẹlu ẹgbẹ wa",
      myWishlist: "Àwọn Ẹrù Ìfẹ́ Mi",
    emptyWishlist: "Àwọn ẹrù ìfẹ́ rẹ ò ní ohunkóhun",
    discoverProducts: "Ṣawari awọn ẹrù",
    moveToCart: "Fi sí Agbọ̀n",
},

  zh: {
    signIn: "登录",
    dashboard: "控制台",
    adminPanel: "管理面板",
    logout: "退出",
    searchPlaceholder: "搜索产品...",
    settings: "设置",
    language: "语言",
    home: "主页",
    shop: "商店",
    products: "产品",
    categories: "分类",
    about: "关于我们",
    cart: "购物车",
    emptyCart: "购物车是空的",
    emptyCartSub: "您还没有添加任何商品。",
    continueShopping: "继续购物",
    removeItem: "删除",
    orderSummary: "订单摘要",
    subtotal: "小计",
    shipping: "运费",
    tax: "税 (15%)",
    total: "总计",
    proceedToCheckout: "去结账",
    freeShipping: "免费",
    secureCheckout: "安全结账",
    shippingInfo: "配送信息",
    paymentMethod: "支付方式",
    placeOrder: "下订单",
    address: "地址",
    city: "城市",
    country: "国家",
    postalCode: "邮政编码（可选）",
    addToCart: "加入购物车",
    buyNow: "立即购买",
    inStock: "有货",
    outOfStock: "缺货",
    description: "描述",
    reviews: "评价",
    specifications: "规格",
    writeReview: "写评价",
    submitReview: "提交评价",
    yourRating: "您的评分",
    yourComment: "您的评论",
    commentPlaceholder: "分享您对此产品的体验...",
    alreadyReviewed: "您已经评价过该产品。谢谢！",
    loginToReview: "您必须登录才能发表评价。",
    noReviews: "暂无评价。成为第一个！",
    reviewSuccess: "您的评价已提交！谢谢。",
    selectRating: "请选择星级评分。",
    writeComment: "请写一条评论。",
    poor: "差",
    fair: "一般",
    good: "良好",
    veryGood: "很好",
    excellent: "优秀",
    loading: "加载中...",
    submitting: "提交中...",
    viewAll: "查看全部",
    shopNow: "立即购买",
    newArrivals: "新品上架",
    featuredProducts: "特色产品",
    noProductsFound: "未找到产品。",
    price: "价格",
    quantity: "数量",

    // Added
    freeDelivery: "免费送货",
    freeDeliverySub: "单笔订单满 $500",
    securePayments: "安全支付",
    securePaymentsSub: "100% 保障转账安全",
    optimusTransfer: "Optimus 银行转账",
    optimusTransferSub: "账号: 2002245072 · Donald Ekemini David",
    brandDescription: "优质家用电器和家具。为您量身定制美丽、现代的居住空间。",
    quickLinks: "购买",
    allProducts: "所有产品",
    livingRoom: "客厅",
    kitchen: "厨房电器",
    bedroom: "卧室",
    office: "办公",
    support: "支持",
    myAccount: "我的账户",
    trackOrder: "追踪订单",
    returnsExchanges: "退换货",
    contactUs: "联系我们",
    stayConnected: "保持联系",
    subscribeDeals: "订阅优惠和更新",
    go: "订阅",
    copyright: "保留所有权利。",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    cookiePolicy: "Cookie 政策",
    welcomeBack: "欢迎回来",
    joinBIGDON: "加入 BIGDON",
    welcomeBackSub: "登录以访问您的尊享账户",
    joinBIGDONSub: "创建账户以追踪订单并保存愿望清单",
    fullName: "姓名",
    emailAddress: "邮箱地址",
    passwordLabel: "密码",
    confirmPasswordLabel: "确认密码",
    createAccount: "创建账户",
    alreadyHaveAccount: "已有账户？",
    dontHaveAccount: "还没有账户？",
    signUp: "注册",
    logIn: "登录",
    passwordsDoNotMatch: "两次输入的密码不一致",
    filters: "筛选",
    sortBy: "排序方式",
    clearAllFilters: "清除所有筛选",
    searchResultsFor: "搜索结果：",
    shopCollection: "选购系列",
    shopSub: "探索我们的优质产品系列，提升您的空间格调。",
    sortNewest: "新品上架",
    sortLowest: "价格：从低到高",
    sortHighest: "价格：从高到低",
    sortPopular: "最受欢迎",
    noProductsFoundSub: "我们找不到任何符合您筛选条件的产品。",
    shopCollectionBtn: "选购系列",
    shopByCategory: "按分类选购",
    categorySub: "为每个空间精心挑选的必需品。",
    slideTitle1: "提升您的\n生活空间。",
    slideDesc1: "探索专为现代家庭设计的优质家具和电器。",
    slideTitle2: "卓越的\n烹饪体验。",
    slideDesc2: "为热情洋溢的家庭主厨准备的先进厨房电器。",
    slideTitle3: "静谧的\n休憩之所。",
    slideDesc3: "用我们的奢华系列打造您完美的卧室避风港。",
    yearWarranty: "1 年保修",
    warrantySub: "保证产品质量",
    securePaymentsBadge: "安全支付",
    securePaymentsBadgeSub: "100% 安全结账",
    supportBadge: "24/7 客户支持",
    supportBadgeSub: "与我们的团队进行实时聊天",
      myWishlist: "我的愿望清单",
    emptyWishlist: "您的愿望清单是空的",
    discoverProducts: "发现产品",
    moveToCart: "移至购物车",
},
};

// ─────────────────────────────────────────────
//  Context
// ─────────────────────────────────────────────
export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState("en");

  // Persist across page refreshes
  useEffect(() => {
    const saved = localStorage.getItem("bigdon_lang");
    if (saved && translations[saved]) {
      setLang(saved);
      const langObj = LANGUAGES.find((l) => l.code === saved);
      document.documentElement.dir = langObj?.dir || "ltr";
      document.documentElement.lang = saved;
    }
  }, []);

  const changeLanguage = (code) => {
    if (!translations[code]) return;
    setLang(code);
    localStorage.setItem("bigdon_lang", code);

    // Handle RTL for Arabic
    const langObj = LANGUAGES.find((l) => l.code === code);
    document.documentElement.dir = langObj?.dir || "ltr";
    document.documentElement.lang = code;
  };

  const t = (key) => translations[lang]?.[key] ?? translations["en"][key] ?? key;

  const currentLang = LANGUAGES.find((l) => l.code === lang) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t, currentLang, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Convenience hook
export const useLanguage = () => useContext(LanguageContext);
